title: "Comunidad de Ciberdefensa"
email: "tu.email@example.com"
description: "Noticias, tools y charlas de ciberdefensa — Comunidad técnica."
baseurl: "" # no dejes slash al final
url: "" # ejemplo: "https://tusitio.com" si usas dominio propio
theme: minima
plugins: []
paginate: 5
author:
  name: "Nombre de la Comunidad"
  email: "tu.email@example.com"
